### ISSUE TITLE
Vendor issue

### ISSUE THREAD

**Issue by CurleyDS** [MikedeJong14/studenten-portaal#18]
Describe the bug
The vendor map was changed to change styling of navigation bar. Vendor map is not allowed to be changed!

To Reproduce
Go to the dashboard page on http://studenten-portaal.herokuapp.com

Expected behavior
n.v.t

Desktop (please complete the following information):

OS: Windows 10
Browser Google Chrome
Version 0.0.9.2

**Comment by 99051257** [comment]
#20
