### ISSUE TITLE
Searching a question with answer does not show the answer

### ISSUE THREAD

**Issue by MikedeJong14** [MikedeJong14/studenten-portaal#19]
**Describe the bug**
When using the search bar in the navbar to search for a question, when the quesiton is found and shown it does not show an answer.

**To Reproduce**
1. Go to the dashboard page on http://studenten-portaal.herokuapp.com/dashboard and log in
2. Click on the search bar in the navbar
3. Search a question with an answer to it
4. The question is then shown if found

**Expected behavior**
As you search a question, if that question has an answer, both the question and answer should be shown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 0.0.9.2

**Comment by RutgerVos** [comment]
in the new version 0.0.9.3 this bug is fixed  and if you search for a question and it has  a answer it wil show it underneath the question.
