### ISSUE TITLE
Afspraak bewerken geeft verkeerde docent weer

### ISSUE THREAD

**Issue by MikedeJong14** [MikedeJong14/studenten-portaal#31]
**Describe the bug**
Als ik een afspraak maak met welke docent dan ook, bij het bewerken geeft het veld automatisch aan docent "martijn"
Ik moet dus handmatig die steeds veranderen

**To Reproduce**
1. Ga naar http://studenten-portaal.herokuapp.com/planning/kalender en maak een nieuwe afspraak
2. Ga vervolgens naar http://studenten-portaal.herokuapp.com/planning en bewerk de afspraak
3. Bij de "docent" links onder in de dropdown staat 'martijn' altijd aangevinkt

**Expected behavior**
De docent die ik heb aangegeven staat wel bij de afspraak overzicht, maar verkeerd in de bewerk formulier

**Desktop:**
 - OS: Windows 10
 - Browser Google Chrome
 - Version Laatste release op de test omgeving

**Comment by CurleyDS** [comment]
We hebben het doorgelezen en hebben gevonden dat de aangegeven docent niet geselecteerd staat. We zullen dit fixen in de eerstvolgende release, bedankt voor uw hulp.
